language: php

php:
  - 7
  - 5.6

env:
  - LARAVEL_VERSION="~5.2" TESTBENCH_VERSION="~3.2"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script: phpunit

sudo: false

notifications:
  slack: asgardcms:rQqM7V2EoZOrsv6GgAemZyOS
  email:
    - n.widart@gmail.com
    - josh@joshbrown.me
